### ISSUE TITLE
qt5.15.2(8.01) with 8.0 plugin get crashed

### ISSUE THREAD

**Issue by Accendo98** [ros-industrial/ros_qtc_plugin#466]
qt5.15.2

version8.0.1

ros_qtc_plugin8.0

After installing the 8.0 ros_qtc_plugin,I clicked  to create new project and QT got crashed.
segmentation fault(core dumped)
I dont know why.

**Comment by christian-rauch** [comment]
How did you install it (snap, everything compiled manually, use the binary package with the official installer)?

Can you provide a gdb backtrace?

Can you also describe the steps in more detail? I created a new project/workspace without issues using the snap package.

**Comment by Accendo98** [comment]
> How did you install it (snap, everything compiled manually, use the binary package with the official installer)?
> 
> Can you provide a gdb backtrace?
> 
> Can you also describe the steps in more detail? I created a new project/workspace without issues using the snap package.

I install it again,using the snap package and the problem has been solved,thx.

**Comment by christian-rauch** [comment]
I encountered a crash when simply trying to create a new project via <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd> in Qt Creator distributed by the official online installer.

But the backtrace does not show anything related to this plugin:
```c
#0  0x00007ffff6b77e8c in QIcon::actualSize(QSize const&, QIcon::Mode, QIcon::State) const () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Gui.so.6
#1  0x00007ffff7817092 in QStyledItemDelegate::initStyleOption(QStyleOptionViewItem*, QModelIndex const&) const () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#2  0x00007ffff781604a in QStyledItemDelegate::sizeHint(QStyleOptionViewItem const&, QModelIndex const&) const () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#3  0x00007ffff78277c8 in  () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#4  0x00007ffff78279c0 in  () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#5  0x00007ffff78220d4 in  () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#6  0x00007ffff782e236 in QListView::doItemsLayout() () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#7  0x00007ffff7825b45 in QListView::visualIndex(QModelIndex const&) const () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#8  0x00007ffff782fc69 in QListView::selectionChanged(QItemSelection const&, QItemSelection const&) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#9  0x00007ffff6300610 in  () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#10 0x00007ffff64f32c0 in QItemSelectionModel::selectionChanged(QItemSelection const&, QItemSelection const&) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#11 0x00007ffff64fa7d5 in QItemSelectionModel::select(QItemSelection const&, QFlags<QItemSelectionModel::SelectionFlag>) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#12 0x00007ffff64f957e in QItemSelectionModel::select(QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#13 0x00007ffff64f4715 in QItemSelectionModel::setCurrentIndex(QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#14 0x00007ffff77e089f in QAbstractItemView::setCurrentIndex(QModelIndex const&) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#15 0x00007fffe815476c in Core::Internal::NewDialogWidget::currentCategoryChanged(QModelIndex const&) (index=<optimized out>, this=<optimized out>)
    at /home/qt/work/build/qt-creator/src/plugins/coreplugin/dialogs/newdialogwidget.cpp:392
#16 Core::Internal::NewDialogWidget::currentCategoryChanged(QModelIndex const&) (this=<optimized out>, index=<optimized out>)
    at /home/qt/work/build/qt-creator/src/plugins/coreplugin/dialogs/newdialogwidget.cpp:385
#17 0x00007ffff630029a in  () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#18 0x00007ffff64f3303 in QItemSelectionModel::currentChanged(QModelIndex const&, QModelIndex const&) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#19 0x00007ffff64f4662 in QItemSelectionModel::setCurrentIndex(QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#20 0x00007ffff77e089f in QAbstractItemView::setCurrentIndex(QModelIndex const&) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#21 0x00007fffe815a289 in Core::Internal::NewDialogWidget::showDialog() (this=0x2336de0) at /home/qt/work/build/qt-creator/src/plugins/coreplugin/dialogs/newdialogwidget.cpp:317
#22 0x00007fffe824a0df in Core::ICore::showNewItemDialog(QString const&, QList<Core::IWizardFactory*> const&, Utils::FilePath const&, QMap<QString, QVariant> const&)
     (title=..., factories=<optimized out>, defaultLocation=..., extraVariables=...) at /home/qt/work/build/qt-creator/src/plugins/coreplugin/icore.cpp:281
#23 0x00007fffe82bd4eb in operator() (__closure=<optimized out>) at /home/qt/work/build/qt-creator/src/plugins/coreplugin/mainwindow.cpp:534
#24 QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, Core::Internal::MainWindow::registerDefaultActions()::<lambda()> >::call (arg=<optimized out>, f=<optimized out>)
    at /home/qt/work/build/qt_install_dir/include/QtCore/qobjectdefs_impl.h:163
#25 QtPrivate::Functor<Core::Internal::MainWindow::registerDefaultActions()::<lambda()>, 0>::call<QtPrivate::List<>, void> (arg=<optimized out>, f=<optimized out>)
    at /home/qt/work/build/qt_install_dir/include/QtCore/qobjectdefs_impl.h:277
#26 QtPrivate::QFunctorSlotObject<Core::Internal::MainWindow::registerDefaultActions()::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *)
    (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /home/qt/work/build/qt_install_dir/include/QtCore/qobjectdefs_impl.h:444
#27 0x00007ffff630029a in  () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#28 0x00007ffff6fbccc2 in QAction::triggered(bool) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Gui.so.6
#29 0x00007ffff630029a in  () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#30 0x00007ffff6fbccc2 in QAction::triggered(bool) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Gui.so.6
#31 0x00007ffff6fbfa09 in QAction::activate(QAction::ActionEvent) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Gui.so.6
#32 0x00007ffff76f6712 in  () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#33 0x00007ffff76fddd1 in  () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#34 0x00007ffff7592b08 in QWidget::event(QEvent*) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#35 0x00007ffff753f2d2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#36 0x00007ffff75479b0 in QApplication::notify(QObject*, QEvent*) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#37 0x00007ffff62a16ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#38 0x00007ffff7546c84 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
    at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#39 0x00007ffff75a50ad in  () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#40 0x00007ffff75a711b in  () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#41 0x00007ffff753f2d2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Widgets.so.6
#42 0x00007ffff62a16ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#43 0x00007ffff6bfd350 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Gui.so.6
#44 0x00007ffff6c511dc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Gui.so.6
#45 0x00007ffff21b2a2a in  () at /home/christian/Qt/Tools/QtCreator/lib/Qt/plugins/platforms/../../lib/libQt6XcbQpa.so.6
#46 0x00007ffff2fdbd1b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007ffff30306f8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007ffff2fd93c3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007ffff6545d3a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#50 0x00007ffff62ad96b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#51 0x00007ffff62a952e in QCoreApplication::exec() () at /home/christian/Qt/Tools/QtCreator/bin/../lib/Qt/lib/libQt6Core.so.6
#52 0x000000000040cebb in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/qt/work/build/qt-creator/src/app/main.cpp:790
```

**Comment by christian-rauch** [comment]
This crash seems to only happen with version 8.0.1 but not with 8.0.0. Since plugins are supposed to be ABI compatible across minor versions, I assume this is an issue in Qt Creator: https://bugreports.qt.io/browse/QTCREATORBUG-28169
